package forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class HelpForm extends JFrame {
    private JPanel mainPanel;
    private JTextPane helpTextPane;

    public HelpForm() {
        this.setTitle("Помощь");
        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-5638753));
        mainPanel.setEnabled(false);
        Font mainPanelFont = this.$$$getFont$$$("Comic Sans MS", -1, 18, mainPanel.getFont());
        if (mainPanelFont != null) mainPanel.setFont(mainPanelFont);
        mainPanel.setForeground(new Color(-16730829));
        helpTextPane = new JTextPane();
        helpTextPane.setBackground(new Color(-2359335));
        Font helpTextPaneFont = this.$$$getFont$$$("Comic Sans MS", -1, 16, helpTextPane.getFont());
        if (helpTextPaneFont != null) helpTextPane.setFont(helpTextPaneFont);
        helpTextPane.setForeground(new Color(-16730829));
        helpTextPane.setText("F.A.Q.\n\nВ: Как подключиться к базе данных?\nО: Нажмите кнопку \"Войти/Сменить пользователя\". По умолчанию указаны логин/пароль администратора БД. Чтобы войти в качестве ветерианара, введите:\nлогин: VET \nпароль vet\nЧтобы войти в качестве менеджера зоопарка, введите:\nлогин: MANAGER\nпароль: manager\nИмя схемы и адрес подключения при этом вводить заново не требуется.\n\nВ: Как получить доступ к таблицам базы данных?\nО: Полный доступ к таблицам базы данных имеет лишь администратор БД. Для этого после подключения в качестве администратора БД нажмите кнопку \"Загрузить данные\", после выберите нужную таблицу,и нажмите кнопку \"Открыть таблицу\". Если вы зашли за одну из двух других ролей, воспользуйтесь формами для просмотра данных.\n\nВ: Что делать, если я хочу подключиться за другого пользователя?\nО: Нажмите кнопку \"Войти/Сменить пользователя\", введите необходимые данные, после этого отображаемая информация автоматически изменится в соответствии с вашей ролью.\n\nОбщая информация:\nДля каждой из ролей существует управленческая вкладка со всеми доступными вашей роли действиями. Эта вкладка открывается сразу же после подключения к базе данных. \n\nУдачного пользования!");
        mainPanel.add(helpTextPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(700, 700), new Dimension(700, 700), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
