package view.filters;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import view.FrameLocation;
import view.tables.TableViewForm;

import javax.swing.*;
import java.awt.*;

public class AnimalFilterForm extends JFrame {
    private JPanel mainPanel;
    private JCheckBox notWarmCageButton;
    private JCheckBox warmCageButton;
    private JButton acceptButton;
    private final TableViewForm tableView;

    public AnimalFilterForm(TableViewForm tableView) {
        this.tableView = tableView;
        $$$setupUI$$$();
        this.setTitle("Фильтрация животных");
        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initButtons();
        this.pack();
        FrameLocation.centerFrameLocation(this);
    }

    private void initButtons() {
        acceptButton.addActionListener(e -> acceptFilter());
    }


    private void acceptFilter() {
        String whereClause = " where 1=1 ";

        if (!((warmCageButton.isSelected()) && (notWarmCageButton.isSelected()))) {
            if (notWarmCageButton.isSelected()) {
                whereClause += " and req_warm_cage = 0";
            } else {
                whereClause += " and req_warm_cage = 1";
            }
        }

        tableView.filterTable(whereClause);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        notWarmCageButton = new JCheckBox();
        notWarmCageButton.setSelected(true);
        notWarmCageButton.setText("Не требует теплое помещение");
        mainPanel.add(notWarmCageButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        warmCageButton = new JCheckBox();
        warmCageButton.setSelected(true);
        warmCageButton.setText("Требует теплое помещение");
        mainPanel.add(warmCageButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        acceptButton = new JButton();
        acceptButton.setText("Применить фильтр");
        mainPanel.add(acceptButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
