package view.tables;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entities.Animal;
import entities.Entity;
import view.FrameLocation;
import view.filters.AnimalFilterForm;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.Objects;

public class AnimalForm extends JPanel implements NewEntityPanel {
    private JPanel mainPanel;
    private JLabel typeLabel;
    private JLabel animalNameLabel;
    private JTextField animalNameText;
    private JComboBox<String> typeBox;
    private JCheckBox reqWarmCageCheck;
    private AnimalFilterForm filterForm;

    public AnimalForm() {
        $$$setupUI$$$();

        this.add(mainPanel);
        this.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setMinimumSize(new Dimension(600, 200));
        typeLabel = new JLabel();
        typeLabel.setText("Тип животного");
        mainPanel.add(typeLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        animalNameLabel = new JLabel();
        animalNameLabel.setText("Название животного");
        mainPanel.add(animalNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        animalNameText = new JTextField();
        animalNameText.setMargin(new Insets(2, 6, 2, 6));
        mainPanel.add(animalNameText, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        typeBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Хищник");
        defaultComboBoxModel1.addElement("Травоядное");
        typeBox.setModel(defaultComboBoxModel1);
        mainPanel.add(typeBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        reqWarmCageCheck = new JCheckBox();
        reqWarmCageCheck.setText("Требует теплое помещение на зиму");
        mainPanel.add(reqWarmCageCheck, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    @Override
    public Entity getEntity() {
        return new Animal(
                animalNameText.getText().trim(),
                Objects.requireNonNull(typeBox.getSelectedItem()).toString(),
                reqWarmCageCheck.isSelected() ? 1 : 0
        );
    }

    @Override
    public void insertEntity() throws SQLException {
        getEntity().insertValues();
    }

    @Override
    public void initFilterForm(TableViewForm tableView) {
        filterForm = new AnimalFilterForm(tableView);
    }

    @Override
    public JFrame getFilterForm() {
        return filterForm;
    }
}
