package view.tables;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import entities.Entity;
import entities.Feed;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.util.Objects;

public class FeedForm extends JPanel implements NewEntityPanel {
    private JLabel typeLabel;
    private JLabel feedNameLabel;
    private JTextField feedNameText;
    private JComboBox<String> typeBox;
    private JPanel mainPanel;

    public FeedForm() {
        $$$setupUI$$$();

        this.add(mainPanel);
        this.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        typeLabel = new JLabel();
        typeLabel.setText("Тип корма");
        mainPanel.add(typeLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        feedNameLabel = new JLabel();
        feedNameLabel.setText("Название корма");
        mainPanel.add(feedNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        feedNameText = new JTextField();
        feedNameText.setMargin(new Insets(2, 6, 2, 6));
        mainPanel.add(feedNameText, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        typeBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Растительный");
        defaultComboBoxModel1.addElement("Живой");
        defaultComboBoxModel1.addElement("Мясо");
        defaultComboBoxModel1.addElement("Комбикоpм");
        typeBox.setModel(defaultComboBoxModel1);
        mainPanel.add(typeBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    @Override
    public Entity getEntity() {
        return new Feed(
                feedNameText.getText(),
                Objects.requireNonNull(typeBox.getSelectedItem()).toString()
        );
    }

    @Override
    public void initFilterForm(TableViewForm tableView) {

    }

    @Override
    public void insertEntity() throws SQLException {
        getEntity().insertValues();
    }

    @Override
    public JFrame getFilterForm() {
        return null;
    }
}
