package forms.filters;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import server.Queries;
import forms.FrameLocation;
import forms.tables.TableViewForm;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class AnimalAnimalFilterForm extends JFrame {
    private JComboBox<String> animalBox;
    private JLabel animalNameLabel;
    private JButton acceptButton;
    private JPanel mainPanel;
    private final TableViewForm tableView;

    public AnimalAnimalFilterForm(TableViewForm tableView) {
        this.tableView = tableView;
        $$$setupUI$$$();
        this.setTitle("Фильтрация совместимых животных");
        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComboBox();
        initButtons();
        this.pack();
        FrameLocation.centerFrameLocation(this);
    }

    private void initComboBox() {
        DefaultComboBoxModel<String> defaultComboBoxModel = new DefaultComboBoxModel<>();
        for (String name : Queries.getAnimalNames()) {
            defaultComboBoxModel.addElement(name);
        }
        animalBox.setModel(defaultComboBoxModel);
    }

    private void initButtons() {
        acceptButton.addActionListener(e -> acceptFilter());
    }

    private void acceptFilter() {
        String whereClause = " where 1=1 ";

        whereClause += " and (animal_name_first = '"
                + Objects.requireNonNull(animalBox.getSelectedItem()).toString()
                + "' "
                + " or animal_name_second = '"
                + Objects.requireNonNull(animalBox.getSelectedItem()).toString()
                + "') ";

        tableView.filterTable(whereClause);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        animalNameLabel = new JLabel();
        animalNameLabel.setText("Вид животного");
        mainPanel.add(animalNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        animalBox = new JComboBox();
        mainPanel.add(animalBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        acceptButton = new JButton();
        acceptButton.setText("Применить фильтр");
        mainPanel.add(acceptButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
