package forms.filters;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import server.Queries;
import forms.FrameLocation;
import forms.tables.TableViewForm;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

public class EmployeeAnimalFilterForm extends JFrame {
    private final TableViewForm tableView;
    private JLabel animalLabel;
    private JLabel dateLabel;
    private JComboBox<String> animalBox;
    private JButton acceptButton;
    private JRadioButton dateButton;
    private JFormattedTextField dateStartText;
    private JFormattedTextField dateEndText;
    private JLabel fromDate;
    private JPanel mainPanel;

    public EmployeeAnimalFilterForm(TableViewForm tableView) {
        this.tableView = tableView;
        $$$setupUI$$$();
        this.setTitle("Фильтрация ответственных за вид");
        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComboBox();
        initButtons();
        this.pack();
        FrameLocation.centerFrameLocation(this);
    }

    private void initComboBox() {
        final DefaultComboBoxModel<String> defaultComboBoxModel = new DefaultComboBoxModel<>();
        defaultComboBoxModel.addElement("Все");
        for (String name : Queries.getAnimalNames()) {
            defaultComboBoxModel.addElement(name);
        }
        animalBox.setModel(defaultComboBoxModel);
    }

    private void initButtons() {
        acceptButton.addActionListener(e -> {
            acceptFilter();
        });
    }

    private void acceptFilter() {
        String whereClause = " where 1=1 ";
        if (!"Все".equalsIgnoreCase(Objects.requireNonNull(animalBox.getSelectedItem()).toString())) {
            whereClause += " and animal_name = '"
                    + Objects.requireNonNull(animalBox.getSelectedItem()).toString() + "'";
        }

        if (!dateButton.isSelected()) {
            whereClause += " and date_start >= to_date('"
                    + dateStartText.getText() + "', 'YYYY-MM-DD')"
                    + " and date_end <= to_date('" + dateEndText.getText() + "', 'YYYY-MM-DD')";
        }
        tableView.filterTable(whereClause);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        animalLabel = new JLabel();
        animalLabel.setText("Вид животного");
        mainPanel.add(animalLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dateLabel = new JLabel();
        dateLabel.setText("Даты ответственности");
        mainPanel.add(dateLabel, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        animalBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        animalBox.setModel(defaultComboBoxModel1);
        mainPanel.add(animalBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        acceptButton = new JButton();
        acceptButton.setText("Применить фильтр");
        mainPanel.add(acceptButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dateButton = new JRadioButton();
        dateButton.setSelected(true);
        dateButton.setText("Любая дата");
        mainPanel.add(dateButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.add(dateStartText, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panel1.add(dateEndText, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fromDate = new JLabel();
        fromDate.setText("С:");
        panel1.add(fromDate, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("До:");
        panel1.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        dateStartText = new JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd"));
        dateStartText.setValue(new Date(0));

        dateEndText = new JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd"));
        dateEndText.setValue(new Date());
    }
}
