package forms.rolepanels;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import forms.MainForm;
import forms.panel.AnimalFeedForm;
import forms.panel.NewEntityForm;
import forms.tables.AnimalCardFeedForm;
import forms.tables.AnimalCardForm;
import forms.tables.AnimalCardIllForm;
import forms.tables.TableViewForm;

import javax.swing.*;
import java.awt.*;

public class VetForm extends JPanel {
    private JButton addNewCardButton;
    private JButton showAnimalCardsButton;
    private JPanel mainPanel;
    private JButton feedButton;
    private JButton addFeedButton;
    private JButton addTreatmentButton;
    private final MainForm mainForm;

    public VetForm(MainForm mainForm) {
        this.mainForm = mainForm;
        this.add(mainPanel);
        initButtons();
    }

    private void initButtons() {
        addNewCardButton.addActionListener(e -> {
            NewEntityForm newEntityForm = new NewEntityForm(new AnimalCardForm());
            mainForm.addNewTab("Добавление особи", newEntityForm);
        });

        showAnimalCardsButton.addActionListener(e -> {
            TableViewForm tableViewForm = new TableViewForm("Карточки животных");
            mainForm.addNewTab("Карточки животных", tableViewForm);
        });

        feedButton.addActionListener(e -> {
            AnimalFeedForm animalFeedForm = new AnimalFeedForm(mainForm);
            mainForm.addNewTab("Питание животных", animalFeedForm);
        });

        addFeedButton.addActionListener(e -> {
            AnimalCardFeedForm animalCardFeedForm = new AnimalCardFeedForm(0);
            mainForm.addNewTab("Добавить питание", animalCardFeedForm);
        });


        addTreatmentButton.addActionListener(e -> {
            AnimalCardIllForm animalCardIllForm = new AnimalCardIllForm();
            mainForm.addNewTab("Назначить лечение", animalCardIllForm);
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        addNewCardButton = new JButton();
        addNewCardButton.setText("Регистрация нового животного");
        mainPanel.add(addNewCardButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        showAnimalCardsButton = new JButton();
        showAnimalCardsButton.setText("Просмотр животных");
        mainPanel.add(showAnimalCardsButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        feedButton = new JButton();
        feedButton.setText("Просмотр питания животных");
        mainPanel.add(feedButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addFeedButton = new JButton();
        addFeedButton.setText("Назначить новое питание животным");
        mainPanel.add(addFeedButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addTreatmentButton = new JButton();
        addTreatmentButton.setText("Назначить лечение больным животным");
        mainPanel.add(addTreatmentButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
