package forms.panel;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import server.DBConnection;
import forms.MainForm;
import forms.tables.AnimalCardIllForm;
import forms.tables.ImplTableModel;
import forms.tables.TableUtils;

import javax.sql.RowSetEvent;
import javax.sql.RowSetListener;
import javax.sql.rowset.CachedRowSet;
import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

public class AnimalIllForm extends JPanel implements RowSetListener {
    private JPanel buttonPanel;
    private JButton addTreatButton;
    private JButton updateButton;
    private JScrollPane scrollPane;
    private JTable illAnimalTable;
    private JPanel mainPanel;
    private ImplTableModel model;
    private final MainForm mainForm;

    public AnimalIllForm(MainForm mainForm) {
        this.mainForm = mainForm;
        $$$setupUI$$$();

        initTable();
        initButtons();
        this.add(mainPanel);
        this.setVisible(true);
    }

    private void initButtons() {
        addTreatButton.addActionListener(e -> {
            AnimalCardIllForm animalCardIllForm = new AnimalCardIllForm();
            mainForm.addNewTab("Назначить лечение", animalCardIllForm);
        });

        updateButton.addActionListener(e -> {
            if (model == null) {
                return;
            }
            try {
                model.getTableRowSet().acceptChanges(DBConnection.getConn());
                model.getTableRowSet().commit();
            } catch (SQLException sqle) {
                sqle.printStackTrace();
                MainForm.displayError(sqle);
            } finally {
                initTable();
            }
        });
    }

    private void initTable() {
        try {
            String query = "select card_id, animal_name, illness, date_start, date_end" +
                    " from animal_ill join animal_card using (card_id)";

            CachedRowSet cachedRowSet = TableUtils.getCustomContentsOfTable(query);
            model = new ImplTableModel(cachedRowSet, new Integer[]{0, 1, 2, 3, 4});
            model.addEventHandlersToRowSet(this);
            illAnimalTable.getTableHeader().setReorderingAllowed(false);
            illAnimalTable.setModel(model);
        } catch (SQLException e) {
            MainForm.displayError(e);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(buttonPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        addTreatButton = new JButton();
        addTreatButton.setText("Назначить лечение");
        buttonPanel.add(addTreatButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        updateButton = new JButton();
        updateButton.setText("Обновить");
        buttonPanel.add(updateButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        mainPanel.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        illAnimalTable = new JTable();
        scrollPane.setViewportView(illAnimalTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    @Override
    public void rowSetChanged(RowSetEvent event) {

    }

    @Override
    public void rowChanged(RowSetEvent event) {
        if (model == null) {
            return;
        }
        CachedRowSet currentRowSet = this.model.getTableRowSet();
        try {
            currentRowSet.moveToCurrentRow();
            model.setTableRowSet(model.getTableRowSet());
            illAnimalTable.setModel(model);
        } catch (SQLException ex) {
            MainForm.displayError(ex);
        }
    }

    @Override
    public void cursorMoved(RowSetEvent event) {

    }
}
