package view.panel;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import connection.DBConnection;
import view.MainForm;
import view.tables.NewEntityPanel;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

public class NewEntityForm extends JPanel {
    private JPanel mainPanel;
    private JButton saveButton;
    private final JPanel entityPanel;

    public NewEntityForm(JPanel entityPanel) {
        this.entityPanel = entityPanel;
        $$$setupUI$$$();
        this.add(mainPanel);
        initButtons();

        this.setVisible(true);
    }

    private void initButtons() {
        saveButton.addActionListener(e -> {
            try {
                ((NewEntityPanel) entityPanel).insertEntity();
                DBConnection.getConn().commit();
            } catch (SQLException throwables) {
                try {
                    DBConnection.getConn().rollback();
                } catch (SQLException sqlException) {
                    sqlException.printStackTrace();
                }
                MainForm.displayError(throwables);
                return;
            }
            MainForm.displaySuccess("Запись добавлена!");
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        saveButton = new JButton();
        saveButton.setText("Сохранить");
        mainPanel.add(saveButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mainPanel.add(entityPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
    }
}
