package forms.tables;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import server.DBConnection;
import server.Queries;
import entities.AnimalCardFeed;
import entities.Entity;
import forms.MainForm;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

public class AnimalCardFeedForm extends JPanel implements NewEntityPanel {
    private JPanel mainPanel;
    private JComboBox<String> animalBox;
    private JComboBox<String> feedBox;
    private JTextField amountText;
    private JFormattedTextField timeText;
    private JLabel cardLabel;
    private JLabel feedLabel;
    private JLabel amountLabel;
    private JLabel timeLabel;
    private JButton saveButton;

    public AnimalCardFeedForm(int selectedAnimal) {
        $$$setupUI$$$();

        initComboBox(selectedAnimal);
        initButtons();

        this.add(mainPanel);
        this.setVisible(true);
    }

    private void initButtons() {
        saveButton.addActionListener(e -> {
            try {
                insertEntity();
                DBConnection.getConn().commit();
            } catch (SQLException throwables) {
                try {
                    DBConnection.getConn().rollback();
                } catch (SQLException sqlException) {
                    sqlException.printStackTrace();
                }
                MainForm.displayError(throwables);
                return;
            }
            MainForm.displaySuccess("Запись добавлена!");
        });
    }

    private void initComboBox(int selectedAnimal) {
        DefaultComboBoxModel<String> boxModel = new DefaultComboBoxModel<>();
        for (String card : Queries.getAnimalCards()) {
            boxModel.addElement(card);
        }
        animalBox.setModel(boxModel);
        animalBox.setSelectedIndex(selectedAnimal);

        boxModel = new DefaultComboBoxModel<>();
        for (String card : Queries.getFeedNames()) {
            boxModel.addElement(card);
        }
        feedBox.setModel(boxModel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        animalBox = new JComboBox();
        mainPanel.add(animalBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        feedBox = new JComboBox();
        mainPanel.add(feedBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        amountText = new JTextField();
        mainPanel.add(amountText, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        mainPanel.add(timeText, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cardLabel = new JLabel();
        cardLabel.setText("Животное");
        mainPanel.add(cardLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        feedLabel = new JLabel();
        feedLabel.setText("Корм");
        mainPanel.add(feedLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        amountLabel = new JLabel();
        amountLabel.setText("Количество");
        mainPanel.add(amountLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        timeLabel = new JLabel();
        timeLabel.setText("Время");
        mainPanel.add(timeLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setText("Сохранить");
        mainPanel.add(saveButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


    @Override
    public Entity getEntity() {
        String animalCard = Objects.requireNonNull(animalBox.getSelectedItem()).toString();
        String[] splittedCard = animalCard.split("\\s+");

        return new AnimalCardFeed(
                Integer.parseInt(splittedCard[0]),
                Objects.requireNonNull(feedBox.getSelectedItem()).toString(),
                amountText.getText(),
                timeText.getText()
        );
    }

    @Override
    public void insertEntity() throws SQLException {
        getEntity().insertValues();
    }

    @Override
    public void initFilterForm(TableViewForm tableView) {

    }

    @Override
    public JFrame getFilterForm() {
        return null;
    }

    private void createUIComponents() {
        timeText = new JFormattedTextField(new SimpleDateFormat("HH:mm"));
        timeText.setValue(new Date(0));
    }
}
