package forms.tables;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import server.Queries;
import entities.Entity;
import entities.Supply;
import forms.filters.SupplyFilterForm;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

public class SupplyForm extends JPanel implements NewEntityPanel {
    private JLabel feedLabel;
    private JLabel supplierLabel;
    private JLabel amountLabel;
    private JLabel priceLabel;
    private JTextField amountText;
    private JTextField priceText;
    private JLabel supplyDateLabel;
    private JFormattedTextField supplyDateText;
    private JComboBox<String> supplierBox;
    private JPanel mainPanel;
    private JComboBox<String> feedBox;
    private SupplyFilterForm filterForm;

    public SupplyForm() {
        $$$setupUI$$$();

        this.add(mainPanel);
        this.setVisible(true);
    }

    private void createUIComponents() {
        supplyDateText = new JFormattedTextField(new SimpleDateFormat("yyyy-MM-dd"));
        supplyDateText.setValue(new Date());

        initComboBox();
    }

    private void initComboBox() {
        supplierBox = new JComboBox<>();
        final DefaultComboBoxModel<String> supplierBoxModel = new DefaultComboBoxModel<>();
        for (String name : Queries.getSupplierNames()) {
            supplierBoxModel.addElement(name);
        }
        supplierBox.setModel(supplierBoxModel);

        feedBox = new JComboBox<>();
        final DefaultComboBoxModel<String> feedBoxModel = new DefaultComboBoxModel<>();
        for (String name : Queries.getFeedNames()) {
            feedBoxModel.addElement(name);
        }
        feedBox.setModel(feedBoxModel);
    }

    @Override
    public Entity getEntity() throws SQLException {
        return new Supply(
                Objects.requireNonNull(supplierBox.getSelectedItem()).toString(),
                Objects.requireNonNull(feedBox.getSelectedItem()).toString(),
                amountText.getText(),
                Integer.parseInt(priceText.getText()),
                supplyDateText.getText()
        );
    }

    @Override
    public void insertEntity() throws SQLException {
        getEntity().insertValues();
    }

    @Override
    public void initFilterForm(TableViewForm tableView) {
        filterForm = new SupplyFilterForm(tableView);
    }

    @Override
    public JFrame getFilterForm() {
        return filterForm;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        feedLabel = new JLabel();
        feedLabel.setText("Корм");
        mainPanel.add(feedLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        supplierLabel = new JLabel();
        supplierLabel.setText("Поставщик");
        mainPanel.add(supplierLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        amountLabel = new JLabel();
        amountLabel.setText("Количество");
        mainPanel.add(amountLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        priceLabel = new JLabel();
        priceLabel.setText("Стоимость");
        mainPanel.add(priceLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        amountText = new JTextField();
        mainPanel.add(amountText, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        priceText = new JTextField();
        mainPanel.add(priceText, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        supplyDateLabel = new JLabel();
        supplyDateLabel.setText("Дата поставки");
        mainPanel.add(supplyDateLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        supplyDateText.setFocusLostBehavior(1);
        mainPanel.add(supplyDateText, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mainPanel.add(supplierBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        feedBox.setModel(defaultComboBoxModel1);
        mainPanel.add(feedBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
